# Example usage of the PyDarkDiv library

In [ ]:
# !pip install -e .
import pydarkdiv as pdd
import numpy as np

In [45]:
# Test using a simple dummy dataset of 5 species x 5 points
np.random.seed(42)
data = np.random.randint(0, 2, size=(5, 5))
data

array([[0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 1, 1, 1, 0],
       [1, 0, 1, 1, 1]], dtype=int32)

In [46]:
darkdiv = pdd.DarkDiv(data)

In [47]:
darkdiv.pool

array([[0.09121122, 1.        , 0.63055866, 0.63055866, 0.02275013],
       [1.        , 0.04779035, 0.5       , 0.5       , 1.        ],
       [0.90878878, 0.02275013, 0.36944134, 0.36944134, 1.        ],
       [0.41207045, 1.        , 1.        , 1.        , 0.1870314 ],
       [1.        , 0.25249254, 1.        , 1.        , 1.        ]])

In [48]:
darkdiv.dark

array([[0.09121122,        nan, 0.63055866, 0.63055866, 0.02275013],
       [       nan, 0.04779035, 0.5       , 0.5       ,        nan],
       [0.90878878, 0.02275013, 0.36944134, 0.36944134,        nan],
       [0.41207045,        nan,        nan,        nan, 0.1870314 ],
       [       nan, 0.25249254,        nan,        nan,        nan]])

# Comparing to R DarkDiv
Just to make sure we have implemented the code correctly, lets compare the results with the R implementation of DarkDiv.

```{R}
library(DarkDiv)

data = matrix(c(0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,1,1,1,0,1,0,1,1,1), byrow = T, nrow = 5)

data
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    1    0    0    0
[2,]    1    0    0    0    1
[3,]    0    0    0    0    1
[4,]    0    1    1    1    0
[5,]    1    0    1    1    1

data.frame(data)

```

```{R}
$Pool
             X1         X2        X3        X4         X5
[1,] 0.09121122 1.00000000 0.6305587 0.6305587 0.02275013
[2,] 1.00000000 0.04779035 0.5000000 0.5000000 1.00000000
[3,] 0.90878878 0.02275013 0.3694413 0.3694413 1.00000000
[4,] 0.41207045 1.00000000 1.0000000 1.0000000 0.18703140
[5,] 1.00000000 0.25249254 1.0000000 1.0000000 1.00000000

$Dark
             X1         X2        X3        X4         X5
[1,] 0.09121122         NA 0.6305587 0.6305587 0.02275013
[2,]         NA 0.04779035 0.5000000 0.5000000         NA
[3,] 0.90878878 0.02275013 0.3694413 0.3694413         NA
[4,] 0.41207045         NA        NA        NA 0.18703140
[5,]         NA 0.25249254        NA        NA         NA
```

We can see that the results are accurately reproduced in the Python implementation of the R code.